# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

{{ $serviceType := .Values.proxy.service.type }}
apiVersion: v1
kind: Service
metadata:
  name: orc8r-proxy
  labels:
    app.kubernetes.io/component: proxy
{{ include "labels" . | indent 4 }}
    {{- with .Values.proxy.service.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.proxy.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: proxy
{{ include "selector-labels" . | indent 4 }}
  type: {{ .Values.proxy.service.type }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  ports:
    {{- with .Values.proxy.service.port.clientcert }}
    - name: clientcert
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if (and (eq $serviceType "NodePort") (not (empty .nodePort))) }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
    {{- with .Values.proxy.service.port.open }}
    - name: open
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if (and (eq $serviceType "NodePort") (not (empty .nodePort))) }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
{{- if eq .Values.proxy.service.type "LoadBalancer" }}
  {{- if .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.proxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.proxy.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
